J miszczyszyn branch
awesome-spectral-indices/awesome-spectral-indices pull request #47
Opened 2024-04-04 10:30 UTC by j-miszczyszyn

Hello, second try after little correction

2024-04-04 11:09 UTC, davemlz requested changes
Hi @j-miszczyszyn,

I have reviewed the index and before acceptance there are a few changes that need to be made.

Please let me know when everything is corrected for adding the index!

Cheers!

2024-04-04 11:09 UTC, davemlz commented on src/indices.py
> -        GDVI=SpectralIndex(
Please do not remove existing keys from indices in the list.

2024-04-04 11:09 UTC, davemlz commented on src/indices.py
> -            short_name="GDVI",
Please do not remove existing attributes from indices in the list.

2024-04-04 11:09 UTC, davemlz commented on src/indices.py
> +        GDVI=SpectralIndex(
The key "GDVI" is already existing for the Generalized Difference Vegetation Index (GDVI), please update your key to a unique key.

2024-04-04 11:09 UTC, davemlz commented on src/indices.py
> +    short_name='GDVI',
Please update the `short_name` with the key of the index.

2024-04-04 11:09 UTC, davemlz commented on src/indices.py
> +    long_name='Generalized Difference Vegetation Index ',
This name is from another index. Please update the name with the actual index name.

2024-04-04 11:09 UTC, davemlz commented on src/indices.py
> +    reference='https://doi.org/10.1016/0034-4257(79)90004-X',
This paper does not correspond to the formula presented in the `formula` attribute. Please update the reference doi with the actual source paper of the index.

2024-04-04 11:26 UTC, j-miszczyszyn commented on src/indices.py
> -        GDVI=SpectralIndex(
I did not remove the existing index

2024-04-04 11:26 UTC, j-miszczyszyn commented on src/indices.py
> -            short_name="GDVI",
I did not remove the existing index

2024-04-04 11:56 UTC, j-miszczyszyn commented
Now i see what should I do, but i have the ask. 
What should I call the new index in order not to mislead anyone? I am not the author of tje publication and only used it in research. The article cited is from 1979 and is older than the one listed (2013)

2024-04-04 12:24 UTC, davemlz commented on src/indices.py
> -        GDVI=SpectralIndex(
No, but the key was removed: https://github.com/j-miszczyszyn/awesome-spectral-indices/blob/76b8ca5399391b039c12ad38c9fc822e53be3962/src/indices.py#L435

2024-04-04 12:25 UTC, davemlz commented on src/indices.py
> -            short_name="GDVI",
No, but the `short_name` attribute was removed: https://github.com/j-miszczyszyn/awesome-spectral-indices/blob/76b8ca5399391b039c12ad38c9fc822e53be3962/src/indices.py#L436

2024-04-05 11:56 UTC, j-miszczyszyn commented
Hey,
I checked more publications and understood what the differences are. In the literature we come across GDVI with two patterns, different names but the same abbreviation.

Please take a look at this article DOI: 10.31914/aak.2264
It describes the difference.
![obraz](https://github.com/awesome-spectral-indices/awesome-spectral-indices/assets/40920091/4560f616-4bef-4c3a-ac64-78e6f46b94f4)

Another article also uses the Trucker formula https://link.springer.com/article/10.1007/s40808-015-0029-y

We have been faced with the daunting task of sorting out the indicators. It therefore proposes the index "GDVI_Trucker" to clearly communicate the differences from the GDVI developed by Wu. What do you think?

2024-04-08 12:23 UTC, closed without merging